name: Post ADO comment

on:
  workflow_call:
    inputs:
      ado_organization:
        description: "Azure DevOps organization name"
        required: true
        type: string
      ado_project:
        description: "Azure DevOps project name"
        required: true
        type: string
    outputs:
      api-response:
        description: "API response from post-ado-comment-action"
        value: ${{ jobs.post-comment.outputs.api-response }}
    secrets:
      ado_username:
        required: true
      ado_personal_token:
        required: true

jobs:
  post-comment:
    # Only run when the caller workflow is handling a merged pull request.
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      api-response: ${{ steps.post-ado-comment.outputs.api-response }}
    steps:
      - name: Post comment to the ADO work item
        id: post-ado-comment
        uses: oxctl/post-ado-comment-action@v1
        with:
          ado-organization: ${{ inputs.ado_organization }}
          ado-project: ${{ inputs.ado_project }}
          ado-username: ${{ secrets.ado_username }}
          ado-personal-token: ${{ secrets.ado_personal_token }}
