name: Build and Deploy Frontend

on:
  workflow_call:
    inputs:
      account_type:
        description: 'Prod or nonprod AWS account'
        type: string
      app_name:
        description: 'The name of the app'
        type: string
      aws_account_id:
        description: 'The AWS account id'
        type: string
      aws_parameters:
        description: 'The AWS parameters'
        type: string
      aws_region:
        description: 'The AWS region'
        type: string
      env_type:
        description: 'The environment type, e.g. test, beta, prod'
        type: string
      execution-environment:
        description: 'The GitHub environment to pull variables from'
        type: string
      github_env:
        description: 'The GitHub environment'
        type: string
      ref:
        description: 'The TAG ref'
        type: string
      sha:
        description: 'SHA of the TAG commit'
        type: string

jobs:
  bootstrap:
    concurrency: bootstrap-${{ inputs.github_env }}
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    permissions:
      id-token: write
      contents: read
    outputs:
      s3_artifact_bucket: ${{ steps.query.outputs.s3_artifact_bucket }}
    steps:
      - uses: actions/checkout@v6
      - uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::${{ inputs.aws_account_id }}:role/cad-github-actions-role
          aws-region: ${{ inputs.aws_region }}
      - run: echo AWS_STACK_PREFIX="${{ inputs.app_name }}-${{ inputs.env_type }}-${{ inputs.account_type }}" | tee -a $GITHUB_ENV
      - id: deploy
        run: aws cloudformation deploy
          --capabilities CAPABILITY_NAMED_IAM
          --template-file ./aws/bootstrap.yaml
          --stack-name ${{ env.AWS_STACK_PREFIX }}-bootstrap
          --parameter-overrides file://aws/${{ inputs.aws_parameters }}.json
          --no-fail-on-empty-changeset
          --tags "email-contact=cad-aws@it.ox.ac.uk" "billing=canvas-bau" "application-name=${{ inputs.app_name }}" "environment=${{ inputs.env_type }}"
      - if: failure() && steps.deploy.outcome != 'success'
        # If we had a problem attempt to get a useful list of error messages.
        # YAML seems the most readable in a text console (GitHub Actions log)
        run: aws cloudformation describe-stack-events
          --stack-name ${{ env.AWS_STACK_PREFIX }}-bootstrap
          --output yaml
      - name: Query Cloudformation exports for ECR repository
        id: query
        run: echo s3_artifact_bucket=$(aws cloudformation list-exports --query "Exports[?Name=='${{ env.AWS_STACK_PREFIX }}-bootstrap-dist-bucket-name'].Value" --output text) | tee -a $GITHUB_OUTPUT

  build:
    needs: [ bootstrap ]
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    # This is needed for AWS assume role
    permissions:
      id-token: write
      contents: read
    environment: ${{ inputs.execution-environment }}
    env:
      COMMIT_SHA: ${{ inputs.sha }}
      TAG_REF: ${{ inputs.ref }}
      S3_ARTIFACT_BUCKET: ${{ needs.bootstrap.outputs.s3_artifact_bucket }}
      VITE_SENTRY_DSN: ${{ vars.VITE_SENTRY_DSN }}
      VITE_SENTRY_ENV: ${{ vars.VITE_SENTRY_ENV }}
    defaults:
      run:
        working-directory: frontend
    outputs:
      artifact: ${{ steps.upload.outputs.artifact }}
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ env.COMMIT_SHA }}
      - uses: actions/setup-node@v6
        with:
          node-version-file: 'frontend/.nvmrc'
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - name: Set archive version
        run: echo "ARCHIVE=${{ inputs.app_name }}-${GITHUB_REF#refs/heads/}.${GITHUB_RUN_NUMBER}.tgz" | tee -a $GITHUB_ENV
      - name: Set archive tag version
        if: ${{ startsWith(env.TAG_REF, 'refs/tags/') }}
        run: echo "ARCHIVE=release-${TAG_REF#refs/tags/}.tgz" | tee -a $GITHUB_ENV
      - name: Set archive pull version
        if: ${{ startsWith(github.ref, 'refs/pull/') }}
        run: echo "ARCHIVE=pull-${GITHUB_HEAD_REF}.${GITHUB_RUN_NUMBER}.tgz" | tee -a $GITHUB_ENV
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::${{ inputs.aws_account_id }}:role/cad-github-actions-role
          aws-region: ${{ inputs.aws_region }}
      - name: Upload to AWS S3 Bucket - ${{ env.S3_ARTIFACT_BUCKET }}
        id: upload
        # The name of the archive must include the build number to allow us to cleanup older versions
        run: |
          echo "$ARCHIVE"
          tar -C build -zcvf $ARCHIVE .
          aws s3 cp $ARCHIVE s3://${S3_ARTIFACT_BUCKET}/
          echo artifact="$ARCHIVE" | tee -a $GITHUB_OUTPUT
      - name: Upload AWS artifact
        uses: actions/upload-artifact@v7
        with:
          name: aws-frontend
          path: aws
          retention-days: 1

  deploy:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    needs: [ build, bootstrap ]
    concurrency: frontend-${{ inputs.github_env }}
    # This is needed for AWS assume role
    permissions:
      id-token: write
      contents: read
    env:
      ARCHIVE: ${{ needs.build.outputs.artifact }}
      S3_ARTIFACT_BUCKET: ${{ needs.bootstrap.outputs.s3_artifact_bucket }}
    steps:
      - name: Download AWS artifact
        uses: actions/download-artifact@v8
        with:
          name: aws-frontend
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        id: aws-credentials
        with:
          role-to-assume: arn:aws:iam::${{ inputs.aws_account_id }}:role/cad-github-actions-role
          aws-region: ${{ inputs.aws_region }}
          output-credentials: true
      - run: echo AWS_STACK_PREFIX="${{ inputs.app_name }}-${{ inputs.env_type }}-${{ inputs.account_type }}" | tee -a $GITHUB_ENV
      - id: deploy
        run: aws cloudformation deploy
          --capabilities CAPABILITY_NAMED_IAM
          --template-file ./s3-and-cloudfront.yaml
          --stack-name ${{ env.AWS_STACK_PREFIX }}-frontend
          --parameter-overrides file://${{ inputs.aws_parameters }}.json
          --no-fail-on-empty-changeset
          --tags "email-contact=cad-aws@it.ox.ac.uk" "billing=canvas-bau" "application-name=${{ inputs.app_name }}" "environment=${{ inputs.env_type }}"
      - run: echo S3_BUCKET=$(aws cloudformation list-exports --query "Exports[?Name=='${{ env.AWS_STACK_PREFIX }}-frontend-app-bucket-name'].Value" --output text) | tee -a $GITHUB_ENV
      - name: Download ${{ env.ARCHIVE }} build from S3
        run: aws s3 cp s3://${{ env.S3_ARTIFACT_BUCKET }}/${{ env.ARCHIVE }} build.tgz
      - run: mkdir files
      - name: Unzip files
        run: tar -zxvf build.tgz -C files
      - uses: oxctl/react-deploy-to-s3-action@session-tokens
        env:
          AWS_S3_BUCKET: ${{ env.S3_BUCKET }}
          AWS_REGION: ${{ inputs.aws_region }}
          AWS_ACCESS_KEY_ID: ${{ steps.aws-credentials.outputs.aws-access-key-id }}
          AWS_SECRET_ACCESS_KEY: ${{ steps.aws-credentials.outputs.aws-secret-access-key }}
          AWS_SESSION_TOKEN: ${{ steps.aws-credentials.outputs.aws-session-token }}
          SOURCE_DIR: files

  cleanup-artifacts:
    runs-on: ubuntu-22.04
    needs: [ build ]
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::${{ inputs.aws_account_id }}:role/cad-github-actions-role
          aws-region: ${{ inputs.aws_region }}
      - name: Delete old versions from S3 bucket
        run: aws s3 ls s3://${S3_ARTIFACT_BUCKET}/ | sort -rn | awk -v s3_url="s3://${S3_ARTIFACT_BUCKET}/" '$4 ~ /${{ inputs.app_name }}-/ {print s3_url $4;}' | tee /${{ inputs.github_env }}/stderr | tail -n +21 | xargs -r -n 1 aws s3 rm
